import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { giltubeAPI } from '@/api/giltube';
import { useAuth } from '@/auth/AuthProvider';
import { PressableScale } from '@/components/PressableScale';
import { MediaBadges } from '@/components/MediaBadges';
import { useI18n } from '@/i18n';
import { colors, makeStyles, radii, withAlpha } from '@/theme/tokens';
import { resolveMediaURL } from '@/utils/media';
import { formatPlaybackTime, isResumable } from '@/utils/watchProgress';

export default function SeriesDetailsScreen() {
  const styles = useStyles();
  const { t } = useI18n();
  const { id } = useLocalSearchParams<{ id: string }>(); const insets = useSafeAreaInsets(); const [season, setSeason] = useState(1); const { status } = useAuth(); const signedIn = status === 'signedIn';
  const detail = useQuery({ queryKey: ['series-detail', id], queryFn: () => giltubeAPI.seriesDetail(id), enabled: !!id });
  const show = detail.data?.series; const episodes = useMemo(() => detail.data?.episodes || [], [detail.data?.episodes]);
  const seasons = useMemo(() => [...new Set(episodes.map((episode) => episode.season_number))].sort((a, b) => a - b), [episodes]);
  const episodeIDs = useMemo(() => episodes.map((episode) => episode.video_id).filter(Boolean), [episodes]);
  const progress = useQuery({ queryKey: ['watch-progress-map', episodeIDs.join(',')], queryFn: () => giltubeAPI.watchProgressMap(episodeIDs), enabled: signedIn && episodeIDs.length > 0 });
  const activeSeason = seasons.includes(season) ? season : seasons[0];
  // The most recently watched unfinished episode, as on the website.
  const seriesProgress = useQuery({ queryKey: ['series-progress', show?.id], queryFn: () => giltubeAPI.seriesProgress(show!.id), enabled: signedIn && !!show?.id, retry: false });
  const resumeEpisode = isResumable(seriesProgress.data?.progress) && seriesProgress.data?.episode?.video_id ? seriesProgress.data.episode : null;
  const resumePosition = seriesProgress.data?.progress?.position_seconds || 0;
  const openEpisode = (videoID: string, startOver = false) => router.push({ pathname: '/video/[id]', params: startOver ? { id: videoID, startOver: '1' } : { id: videoID } });
  return <ScrollView style={styles.screen} contentContainerStyle={{ paddingBottom: insets.bottom + 48 }}>
    <View style={[styles.top, { paddingTop: insets.top + 8 }]}><PressableScale onPress={() => router.back()} style={styles.round}><Ionicons name="chevron-back" color={colors.white} size={25} /></PressableScale></View>
    {detail.isLoading && <ActivityIndicator style={styles.loading} color={colors.accentBright} size="large" />}
    {!!show && <><View style={styles.hero}><Image source={resolveMediaURL(show.backdrop_url || show.poster_url)} style={StyleSheet.absoluteFill} contentFit="cover" /><LinearGradient colors={['rgba(0,0,0,.06)', withAlpha(colors.canvas, 0.45), colors.canvas]} locations={[0, .58, 1]} style={StyleSheet.absoluteFill} /></View>
      <View style={styles.copy}><Text style={styles.kicker}>{t('GILTUBE SERIES')}</Text><Text style={styles.title}>{show.title}</Text><Text style={styles.meta}>{show.seasons} {t(show.seasons === 1 ? 'season' : 'seasons')}  ·  {show.episode_count} {t(show.episode_count === 1 ? 'episode' : 'episodes')}  ·  {(show.genres || []).join(' · ')}</Text>
        <View style={styles.buttons}>{resumeEpisode ? <><PressableScale onPress={() => openEpisode(resumeEpisode.video_id)} style={styles.play}><Ionicons name="play" color={colors.onText} size={19} /><Text numberOfLines={1} style={styles.playText}>{t('Resume')} {t('S')}{resumeEpisode.season_number} E{resumeEpisode.episode_number} · {formatPlaybackTime(resumePosition)}</Text></PressableScale><PressableScale accessibilityLabel={t('Start over')} onPress={() => openEpisode(resumeEpisode.video_id, true)} style={styles.trailer}><Ionicons name="refresh" color={colors.text} size={18} /><Text style={styles.trailerText}>{t('Start over')}</Text></PressableScale></> : !!episodes[0]?.video_id && <PressableScale onPress={() => openEpisode(episodes[0].video_id)} style={styles.play}><Ionicons name="play" color={colors.onText} size={19} /><Text style={styles.playText}>{t('Start series')}</Text></PressableScale>}{!!show.trailer_video_id && <PressableScale onPress={() => router.push({ pathname: '/video/[id]', params: { id: show.trailer_video_id } })} style={styles.trailer}><Ionicons name="film-outline" color={colors.text} size={18} /><Text style={styles.trailerText}>{t('Trailer')}</Text></PressableScale>}</View>
        <Text style={styles.synopsis}>{show.synopsis}</Text>{!!show.directors?.length && <Text style={styles.credit}><Text style={styles.creditLabel}>{t('Created by:')} </Text>{show.directors.join(', ')}</Text>}{!!show.cast?.length && <Text style={styles.credit}><Text style={styles.creditLabel}>{t('Cast:')} </Text>{show.cast.join(', ')}</Text>}<MediaBadges capabilities={show.media_capabilities} rating={show.content_rating} explicit={show.explicit} />
      </View>
      <Text style={styles.episodesTitle}>{t('Episodes')}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.seasons}>{seasons.map((number) => <PressableScale key={number} onPress={() => setSeason(number)} style={[styles.season, activeSeason === number && styles.seasonActive]}><Text style={[styles.seasonText, activeSeason === number && styles.seasonTextActive]}>{t('Season')} {number}</Text></PressableScale>)}</ScrollView>
      <View style={styles.episodeList}>{episodes.filter((episode) => episode.season_number === activeSeason).map((episode) => { const watched = progress.data?.progress[episode.video_id]; const percent = watched?.duration_seconds ? Math.min(100, Math.max(0, watched.position_seconds / watched.duration_seconds * 100)) : 0; return <PressableScale key={episode.id} onPress={() => router.push({ pathname: '/video/[id]', params: { id: episode.video_id } })} style={styles.episode}><View style={styles.thumbWrap}><Image source={resolveMediaURL(episode.video?.thumbnail_url || show.backdrop_url)} style={StyleSheet.absoluteFill} contentFit="cover" />{percent > 0 && <View style={styles.watchTrack}><View style={[styles.watchFill, { width: `${percent}%` }]} /></View>}</View><View style={styles.episodeCopy}><Text style={styles.episodeNumber}>{t('S')}{episode.season_number} E{episode.episode_number}{watched?.completed ? ` · ${t('WATCHED')}` : ''}</Text><Text numberOfLines={2} style={styles.episodeTitle}>{episode.title}</Text><Text numberOfLines={2} style={styles.episodeSynopsis}>{episode.synopsis}</Text></View><Ionicons name={watched?.completed ? 'checkmark-circle' : 'play-circle'} color={watched?.completed ? colors.accentBright : colors.text} size={29} /></PressableScale>; })}</View>
    </>}
  </ScrollView>;
}

const useStyles = makeStyles(() => ({ screen: { flex: 1, backgroundColor: colors.screen }, top: { position: 'absolute', zIndex: 4, left: 12, top: 0, height: 64 }, round: { width: 42, height: 42, borderRadius: 21, backgroundColor: 'rgba(0,0,0,.65)', alignItems: 'center', justifyContent: 'center' }, loading: { marginTop: 180 }, hero: { height: 405, backgroundColor: colors.surfaceStrong }, copy: { marginTop: -92, paddingHorizontal: 20 }, kicker: { color: colors.accentBright, fontSize: 9, letterSpacing: 1.6, fontWeight: '900' }, title: { color: colors.text, fontSize: 34, lineHeight: 38, fontWeight: '900', letterSpacing: -1, marginTop: 7 }, meta: { color: colors.textMuted, fontSize: 11, lineHeight: 17, marginTop: 8 }, buttons: { flexDirection: 'row', gap: 10, marginTop: 20 }, play: { flex: 1, height: 48, borderRadius: radii.pill, backgroundColor: colors.text, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, playText: { color: colors.onText, fontSize: 14, fontWeight: '900' }, trailer: { height: 48, paddingHorizontal: 18, borderRadius: radii.pill, backgroundColor: colors.surfaceStrong, flexDirection: 'row', alignItems: 'center', gap: 7 }, trailerText: { color: colors.text, fontSize: 13, fontWeight: '800' }, synopsis: { color: colors.text, fontSize: 15, lineHeight: 23, marginTop: 23 }, credit: { color: colors.textMuted, fontSize: 12, lineHeight: 18, marginTop: 10 }, creditLabel: { color: colors.text, fontWeight: '800' }, episodesTitle: { color: colors.text, fontSize: 23, fontWeight: '900', marginTop: 32, paddingHorizontal: 20 }, seasons: { paddingHorizontal: 20, gap: 9, paddingVertical: 14 }, season: { height: 38, paddingHorizontal: 16, borderRadius: radii.pill, backgroundColor: colors.surface, justifyContent: 'center' }, seasonActive: { backgroundColor: colors.text }, seasonText: { color: colors.textMuted, fontSize: 12, fontWeight: '800' }, seasonTextActive: { color: colors.onText }, episodeList: { paddingHorizontal: 18 }, episode: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, thumbWrap: { width: 116, aspectRatio: 16 / 9, overflow: 'hidden', borderRadius: radii.md, backgroundColor: colors.surfaceStrong }, watchTrack: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 4, backgroundColor: 'rgba(255,255,255,.24)' }, watchFill: { height: '100%', backgroundColor: colors.accentBright }, episodeCopy: { flex: 1 }, episodeNumber: { color: colors.accentBright, fontSize: 9, fontWeight: '900', letterSpacing: 1 }, episodeTitle: { color: colors.text, fontSize: 14, lineHeight: 18, fontWeight: '800', marginTop: 4 }, episodeSynopsis: { color: colors.textMuted, fontSize: 10, lineHeight: 14, marginTop: 5 } }));
