import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { giltubeAPI } from '@/api/giltube';
import { useAuth } from '@/auth/AuthProvider';
import { PressableScale } from '@/components/PressableScale';
import { SwipeSheet } from '@/components/SwipeSheet';
import { useI18n } from '@/i18n';
import { colors, radii } from '@/theme/tokens';

const languages = [{ code: '', name: 'Automatic' }, { code: 'en', name: 'English' }, { code: 'es', name: 'Spanish' }, { code: 'pt', name: 'Portuguese' }, { code: 'fr', name: 'French' }, { code: 'de', name: 'German' }, { code: 'ja', name: 'Japanese' }, { code: 'ko', name: 'Korean' }];

export default function PlaybackSettingsScreen() {
  const insets = useSafeAreaInsets(); const { account, refreshAccount } = useAuth(); const [picker, setPicker] = useState<'audio' | 'captions' | null>(null); const [busy, setBusy] = useState(false);
  const { t } = useI18n();
  const nameFor = (code: string) => t(languages.find((item) => item.code === code)?.name || code || 'Automatic');
  const choose = async (code: string) => { if (!account || !picker) return; setBusy(true); try { await giltubeAPI.updatePlaybackLanguages(picker === 'audio' ? code : account.audio_language || '', picker === 'captions' ? code : account.caption_language || ''); await refreshAccount(); setPicker(null); } catch (error) { Alert.alert(t('Could not save preference'), error instanceof Error ? error.message : t('Please try again.')); } finally { setBusy(false); } };
  return <View style={[styles.screen, { paddingTop: insets.top + 12 }]}><View style={styles.top}><PressableScale onPress={() => router.back()} style={styles.back}><Ionicons name="chevron-back" color={colors.text} size={25} /></PressableScale><View><Text style={styles.heading}>{t('Playback languages')}</Text><Text style={styles.subtitle}>{t('Synced with GilTube desktop')}</Text></View></View><Text style={styles.section}>{t('VIDEO DEFAULTS')}</Text><Setting icon="volume-high-outline" title={t('Audio language')} value={nameFor(account?.audio_language || '')} onPress={() => setPicker('audio')} /><Setting icon="text-outline" title={t('Caption language')} value={nameFor(account?.caption_language || '')} onPress={() => setPicker('captions')} /><Text style={styles.note}>{t('GilTube chooses the closest matching track. Captions remain off when no caption preference is selected.')}</Text><SwipeSheet visible={!!picker} title={t(picker === 'audio' ? 'Audio language' : 'Caption language')} onClose={() => setPicker(null)}><ScrollView>{languages.map((language) => { const current = picker === 'audio' ? account?.audio_language || '' : account?.caption_language || ''; return <PressableScale disabled={busy} key={language.code || 'auto'} onPress={() => void choose(language.code)} style={styles.choice}><Text style={styles.choiceText}>{t(language.name)}</Text>{language.code === current && <Ionicons name="checkmark-circle" color={colors.gilid} size={22} />}</PressableScale>; })}</ScrollView></SwipeSheet></View>;
}
function Setting({ icon, title, value, onPress }: { icon: keyof typeof Ionicons.glyphMap; title: string; value: string; onPress: () => void }) { return <PressableScale onPress={onPress} style={styles.setting}><View style={styles.icon}><Ionicons name={icon} color={colors.text} size={21} /></View><View style={{ flex: 1 }}><Text style={styles.settingTitle}>{title}</Text><Text style={styles.settingValue}>{value}</Text></View><Ionicons name="chevron-forward" color={colors.textDim} size={18} /></PressableScale>; }
const styles = StyleSheet.create({ screen: { flex: 1, paddingHorizontal: 18, backgroundColor: colors.canvas }, top: { flexDirection: 'row', alignItems: 'center', gap: 12 }, back: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, heading: { color: colors.text, fontSize: 24, fontWeight: '900' }, subtitle: { color: colors.textMuted, fontSize: 11, marginTop: 2 }, section: { color: colors.textDim, fontSize: 10, fontWeight: '900', letterSpacing: 1.4, marginTop: 32, marginBottom: 8 }, setting: { minHeight: 70, paddingHorizontal: 14, marginBottom: 10, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, flexDirection: 'row', alignItems: 'center', gap: 12 }, icon: { width: 39, height: 39, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceStrong }, settingTitle: { color: colors.text, fontSize: 14, fontWeight: '800' }, settingValue: { color: colors.gilid, fontSize: 11, marginTop: 4 }, note: { color: colors.textMuted, fontSize: 12, lineHeight: 18, marginTop: 10 }, choice: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, choiceText: { color: colors.text, fontSize: 14, fontWeight: '700' } });
