import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import * as DocumentPicker from 'expo-document-picker';
import { router } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, ScrollView, Switch, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { giltubeAPI } from '@/api/giltube';
import { uploadVideo } from '@/api/upload';
import { useAuth } from '@/auth/AuthProvider';
import { useActiveChannel } from '@/channels/ChannelProvider';
import { PressableScale } from '@/components/PressableScale';
import { useI18n } from '@/i18n';
import { colors, makeStyles, radii } from '@/theme/tokens';

export default function UploadScreen() {
  const styles = useStyles();
  const insets = useSafeAreaInsets(); const { account, status } = useAuth(); const signedIn = status === 'signedIn' && !!account;
  const { t } = useI18n();
  const { channels, activeChannelID } = useActiveChannel(); const categories = useQuery({ queryKey: ['categories'], queryFn: giltubeAPI.categories });
  const [video, setVideo] = useState<DocumentPicker.DocumentPickerAsset>(); const [thumbnail, setThumbnail] = useState<DocumentPicker.DocumentPickerAsset>(); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [channelID, setChannelID] = useState(''); const [categoryID, setCategoryID] = useState(''); const [explicit, setExplicit] = useState(false); const [hidden, setHidden] = useState(false); const [progress, setProgress] = useState(0); const [busy, setBusy] = useState(false);
  const selectedChannel = channelID || activeChannelID;
  const chooseVideo = async () => { const result = await DocumentPicker.getDocumentAsync({ type: 'video/*', copyToCacheDirectory: true }); if (!result.canceled) { setVideo(result.assets[0]); if (!title) setTitle(result.assets[0].name.replace(/\.[^.]+$/, '')); } };
  const chooseThumbnail = async () => { const result = await DocumentPicker.getDocumentAsync({ type: 'image/*', copyToCacheDirectory: true }); if (!result.canceled) setThumbnail(result.assets[0]); };
  const submit = async () => { if (!signedIn) { router.push('/login'); return; } if (!video || !title.trim() || !selectedChannel) { Alert.alert(t('Missing details'), t('Choose a video, title, and publishing channel.')); return; } setBusy(true); try { await uploadVideo({ video, thumbnail, title: title.trim(), description: description.trim(), channelID: selectedChannel, categoryID, explicit, hidden, onProgress: setProgress }); Alert.alert(t('Upload received'), t('GilTube is processing your video. You can follow it in the dashboard.'), [{ text: t('Open dashboard'), onPress: () => router.replace('/dashboard') }]); } catch (error) { Alert.alert(t('Upload failed'), error instanceof Error ? error.message : t('Please try again.')); } finally { setBusy(false); } };
  return <KeyboardAvoidingView style={styles.keyboard} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView style={styles.screen} contentContainerStyle={{ paddingTop: insets.top + 12, paddingBottom: insets.bottom + 44 }} keyboardShouldPersistTaps="handled" keyboardDismissMode="interactive" automaticallyAdjustKeyboardInsets><View style={styles.top}><PressableScale onPress={() => router.back()} style={styles.back}><Ionicons name="chevron-back" color={colors.text} size={25} /></PressableScale><View><Text style={styles.heading}>{t('Upload')}</Text><Text style={styles.subheading}>{t('Publish from your phone')}</Text></View></View>
    <PressableScale onPress={chooseVideo} style={styles.drop}><Ionicons name={video ? 'checkmark-circle' : 'cloud-upload-outline'} color={video ? colors.gilid : colors.accentBright} size={40} /><Text style={styles.dropTitle}>{video?.name || t('Choose a video')}</Text><Text style={styles.dropMeta}>{video ? `${((video.size || 0) / 1024 / 1024).toFixed(1)} MB` : t('MP4, MOV, WebM and other video files')}</Text></PressableScale>
    <Label text={t('TITLE')} /><TextInput value={title} onChangeText={setTitle} placeholder={t('Give your video a title')} placeholderTextColor={colors.textDim} style={styles.input} maxLength={150} />
    <Label text={t('DESCRIPTION')} /><TextInput value={description} onChangeText={setDescription} placeholder={t('Tell viewers about this video')} placeholderTextColor={colors.textDim} style={[styles.input, styles.area]} multiline maxLength={5000} />
    <Label text={t('PUBLISHING CHANNEL')} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{channels.map((channel) => <PressableScale key={channel.id} onPress={() => setChannelID(channel.id)} style={[styles.chip, selectedChannel === channel.id && styles.chipActive]}><Text style={[styles.chipText, selectedChannel === channel.id && styles.chipTextActive]}>{channel.name}</Text></PressableScale>)}</ScrollView>
    <Label text={t('CATEGORY')} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{categories.data?.map((category) => <PressableScale key={category.id} onPress={() => setCategoryID(category.id === categoryID ? '' : category.id)} style={[styles.chip, categoryID === category.id && styles.chipActive]}><Text style={[styles.chipText, categoryID === category.id && styles.chipTextActive]}>{category.name}</Text></PressableScale>)}</ScrollView>
    <PressableScale onPress={chooseThumbnail} style={styles.thumbnail}><Ionicons name="image-outline" color={colors.text} size={22} /><View style={{ flex: 1 }}><Text style={styles.optionTitle}>{thumbnail?.name || t('Custom thumbnail')}</Text><Text style={styles.optionMeta}>{t('Optional image')}</Text></View><Text style={styles.choose}>{t('Choose')}</Text></PressableScale>
    <Toggle title={t('Contains explicit content')} value={explicit} onValueChange={setExplicit} /><Toggle title={t('Upload as hidden')} subtitle={t('Keep it out of public feeds')} value={hidden} onValueChange={setHidden} />
    {busy && <View style={styles.progress}><View style={[styles.progressFill, { width: `${Math.max(2, progress)}%` }]} /></View>}<PressableScale disabled={busy} onPress={() => void submit()} style={[styles.publish, busy && { opacity: .6 }]}>{busy ? <ActivityIndicator color={colors.onAccent} /> : <><Ionicons name="cloud-upload" color={colors.onAccent} size={20} /><Text style={styles.publishText}>{t('Upload video')}</Text></>}</PressableScale>
  </ScrollView></KeyboardAvoidingView>;
}
function Label({ text }: { text: string }) { const styles = useStyles(); return <Text style={styles.label}>{text}</Text>; }
function Toggle({ title, subtitle, value, onValueChange }: { title: string; subtitle?: string; value: boolean; onValueChange: (value: boolean) => void }) { const styles = useStyles(); return <View style={styles.toggle}><View style={{ flex: 1 }}><Text style={styles.optionTitle}>{title}</Text>{subtitle && <Text style={styles.optionMeta}>{subtitle}</Text>}</View><Switch value={value} onValueChange={onValueChange} trackColor={{ true: colors.accent, false: colors.surfaceStrong }} /></View>; }
const useStyles = makeStyles(() => ({ keyboard: { flex: 1, backgroundColor: colors.screen }, screen: { flex: 1, backgroundColor: colors.screen, paddingHorizontal: 18 }, top: { flexDirection: 'row', alignItems: 'center', gap: 12 }, back: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, heading: { color: colors.text, fontSize: 28, fontWeight: '900' }, subheading: { color: colors.textMuted, fontSize: 11, marginTop: 2 }, drop: { height: 190, marginTop: 25, borderRadius: radii.xl, borderWidth: 1, borderStyle: 'dashed', borderColor: colors.borderStrong, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, dropTitle: { color: colors.text, fontSize: 15, fontWeight: '900', marginTop: 12, paddingHorizontal: 20 }, dropMeta: { color: colors.textMuted, fontSize: 11, marginTop: 6 }, label: { color: colors.textDim, fontSize: 9, fontWeight: '900', letterSpacing: 1.4, marginTop: 23, marginBottom: 8 }, input: { minHeight: 50, borderRadius: radii.lg, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, color: colors.text, paddingHorizontal: 14, fontSize: 14 }, area: { height: 110, textAlignVertical: 'top', paddingTop: 14 }, chips: { gap: 8 }, chip: { height: 38, paddingHorizontal: 15, borderRadius: radii.pill, backgroundColor: colors.surface, justifyContent: 'center' }, chipActive: { backgroundColor: colors.text }, chipText: { color: colors.textMuted, fontSize: 11, fontWeight: '800' }, chipTextActive: { color: colors.onText }, thumbnail: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 24, paddingHorizontal: 15, borderRadius: radii.lg, backgroundColor: colors.surface }, optionTitle: { color: colors.text, fontSize: 13, fontWeight: '800' }, optionMeta: { color: colors.textMuted, fontSize: 10, marginTop: 4 }, choose: { color: colors.gilid, fontSize: 11, fontWeight: '900' }, toggle: { minHeight: 64, flexDirection: 'row', alignItems: 'center', marginTop: 10, paddingHorizontal: 15, borderRadius: radii.lg, backgroundColor: colors.surface }, progress: { height: 5, marginTop: 26, borderRadius: 3, overflow: 'hidden', backgroundColor: colors.surfaceStrong }, progressFill: { height: '100%', backgroundColor: colors.gilid }, publish: { height: 54, marginTop: 18, borderRadius: radii.lg, backgroundColor: colors.accent, flexDirection: 'row', gap: 9, alignItems: 'center', justifyContent: 'center' }, publishText: { color: colors.onAccent, fontSize: 15, fontWeight: '900' } }));
